### ISSUE TITLE
dev-python/PyChromecast confilct with the dev-python/pychromecast in Gentoo repository

### ISSUE THREAD

**Issue by zhtengw** [onkelbeh/HomeAssistantRepository#11]
The app-misc/homeassistant depends on dev-python/PyChromecast in this repository. But dev-python/pychromecast in Gentoo repository supply the same files with dev-python/PyChromecast.
Change the package name to lowercase may fix it.

**Comment by onkelbeh** [comment]
Sure, could be.
I'll take a deeper look during the weekend.

**Comment by onkelbeh** [comment]
From https://github.com/onkelbeh/HomeAssistantRepository/issues/12 I assume that your are currently needing pychromecast-4.2.0. Older versions untouched. The 'bad' one has a revdep in pulseaudio.

Fixed / cleaned up in https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/0ed820a1a6b58942f6533c0c9c2796827ef5d6b1, will go to the next release.
