### ISSUE TITLE
www-servers/tornado moved to dev-python/tornado

### ISSUE THREAD

**Issue by rastio** [onkelbeh/HomeAssistantRepository#129]
Hello,

www-servers/tornado has been moved to dev-python/tornado in portage tree. Can you please update dependencies such as the one below:
https://github.com/onkelbeh/HomeAssistantRepository/blob/d53f96df187a40b268553307d1b61e11373eb2c1/dev-embedded/esphome/esphome-2022.8.0.ebuild#L42
Thanks for all the work

Rasto

**Comment by onkelbeh** [comment]
let us die the old one in it's used home: https://github.com/onkelbeh/HomeAssistantRepository/commit/931f0b3ffcb96274fd82e786c21651885f358c24

**Comment by onkelbeh** [comment]
fixed shellcheck: https://github.com/onkelbeh/HomeAssistantRepository/commit/c8a46bc530508973f2e0b8c9f67b17e3cd63d002
