### ISSUE TITLE
braviatv dependency

### ISSUE THREAD

**Issue by rastio** [onkelbeh/HomeAssistantRepository#13]
in file app-misc/homeassistant/homeassistant-0.108.9.ebuild

braviatv? ( ~dev-python/braviatv-1.0.1 )

should be

braviatv? ( ~dev-python/bravia-tv-1.0.1 )

**Comment by onkelbeh** [comment]
Yep, Typo. Fixed in https://github.com/onkelbeh/HomeAssistantRepository/commit/bc3f4704844a871b096f0e015f513d362b60b35d

**Comment by rastio** [comment]
Thank you for working on this project. I have just started to explore homeassistant, hoping to build some specific current sensors/switches/relays to finally finish my long term project of controlling window shutters :).
Have fun
Rasto
