### ISSUE TITLE
blebox-uniapi

### ISSUE THREAD

**Issue by Shaggy013** [onkelbeh/HomeAssistantRepository#150]
blebox-uniapi

needs pip and pytest-runner

and latest is 2.1.2

currently building your repo on a quartz64-a rockchip 3566 quad arm a55

**Comment by onkelbeh** [comment]
Thanks for reporting, pytest-runner is mostly installed, so this one went through the tests undiscovered.

202 ist the correct version for [2022.10.4](https://github.com/home-assistant/core/blob/2022.10.4/homeassistant/components/blebox/manifest.json), it will be upgraded soon to 2.10.
