### ISSUE TITLE
dev-python/bleak-retry-connector

### ISSUE THREAD

**Issue by Shaggy013** [onkelbeh/HomeAssistantRepository#154]
you got 

2.13 in homeasssitant ebuild but you updated the dev-python/bleak-retry-connector to 2.3.1

and dev-python/bleak 0.18 in homeassistant ebuild

and aiohomekit wants bleak 0.19 and 2.3.0 from bleak-retry-connector

**Comment by onkelbeh** [comment]
Seems I took the dev deps by mistake.

**Comment by Shaggy013** [comment]
ah well it are a lot of packages

the normal did build fine only it has the bug that it didnt pass the second config about location in the first setup .
 only have to find out how mqtt goes in gentoo 

and trying the full build now but that has a lot of fixes needed :)

**Comment by onkelbeh** [comment]
Full won't do (see README.md), this is thought as a template to make your own useflags.
