### ISSUE TITLE
Update README because python 3.7 is actually standard on gentoo

### ISSUE THREAD

**Issue by zen2** [onkelbeh/HomeAssistantRepository#16]
I think it would be good for newcomers to update installation documentation related to python 3.7 that is now the default version on gentoo so that we don't need anymore to force it to be using:
- /etc/portage/make.conf (USE_PYTHON)
- /etc/portage/profile/use.stable.mask

So resulting documentation can be clearer by removing these parts:
- Python 3.7
- Upgrading to Python 3.7
- Installation on Python 3.6 (deprecated)

Good job anyway :)

**Comment by onkelbeh** [comment]
:-)
You should be used to outdated documentation if you use HA's doku.
I already [removed a lot of it](https://git.edevau.net/onkelbeh/HomeAssistantRepository/commit/068712d72b7b65d435f331505b62e77b10dd39e7).

Will cleanup more.

**Comment by zen2** [comment]
I'm agree that I'm used to outdated documentation with HA ;)
Your repo is one of the best proper installation way to have HA installed on a real linux system.
For a gentoo addict as me it's the way to go.
So I play the game to help you in order to have a good and clean project. ;)

**Comment by onkelbeh** [comment]
For now, I killed some more Python 3.6 doku: https://github.com/onkelbeh/HomeAssistantRepository/commit/06a80b566f3a47a0f1061172df255a9361c0ba0c
