### ISSUE TITLE
Is it possible to add an ebuild for zigbee2mqtt ?

### ISSUE THREAD

**Issue by zen2** [onkelbeh/HomeAssistantRepository#17]
Since I use your overlay, I wish to have an ebuild for zigbee2mqtt that I use, install and update actually by hand:
https://www.zigbee2mqtt.io/
https://github.com/koenkk/zigbee2mqtt

**Comment by onkelbeh** [comment]
I am using zigbee2mqtt, I have an Sigma Designs, Inc. Aeotec Z-Stick Gen5 (ZW090) - UZB attached to a real machine, which is not connected to the HA repo.
All my HA boxes do not have an USB port.

I followed the instructions at https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html

and added a startscript:
```
root@ms3:/etc/init.d # cat zigbee2mqtt
#!/sbin/openrc-run

user="zigbee"
group="zigbee"
command="/usr/bin/npm"
directory="/opt/${RC_SVCNAME}"
command_args="start"
command_user="${user}:${group}"
command_background="yes"
pidfile="/run/${RC_SVCNAME}.pid"
output_log="/var/log/${RC_SVCNAME}.log"
error_log="${output_log}"

depend() {
 use net
}
```
Currently I have nodejs-12.16.1. A bit fishy, but it runs so good I forgot about it.
I will upgrade and look into making an ebuild.

**Comment by zen2** [comment]
I'm currently using zigbee2mqtt installed manually too with my own init.d/conf.d scripts too.
My box works with gentoo ~amd64 with your repository for HA.
So actually zigbee2mqtt works with net-libs/nodejs-14.4.0 perfectly.

To have an ebuild for zigbee2mqtt, at least a -9999 version can be a must have since it's really popular to have ha+zigbee2mqtt combo. That's why you can find zigbee2mqtt ready to install on hassbian for example.

I'm not enough fluent in ebuild to start to write an ebuild with npm usage.
In case I found this project that can be interesting to create such ebuild:
https://github.com/geaaru/node-ebuilder

**Comment by onkelbeh** [comment]
This will take some time, I hardly managed it to work again after upgrading to version 1.14.0 (commit #9009de2) by hand today :-)

I know about some discussions of a npm eclass in 2006, but as far as I know, it is current not used.
Seems nodejs module management inside Portage is not easy, but should be possible.
My colleagues with knowledge in NodeJS do not have knowledge in Portage.
I will take a look at https://github.com/geaaru/node-ebuilder and the repo around it.

**Comment by onkelbeh** [comment]
BTW: same for zwavejs2mqtt:

```bash
git clone https://github.com/zwave-js/zwavejs2mqtt
cd zwavejs2mqtt
yarn install
yarn run build
yarn start
```
I searched the whole tree for an Ebuild to use as a template for yarn builds.
This stuff is made to run in a browser and not for daemons!
Have it on a small storage box running in a screen session, this box is booted only 2-3 times a year, currently I start it after each reboot.

**Comment by zen2** [comment]
btw this is the openrc init.d/conf.d that I currently use for zigbee2mqtt.
It's should be enough generic to use it for different daemons.
And the gentoo way to have init.d script parameters is to put parameters in /etc/conf.d/, not in the init.d script.

**/etc/init.d/zigbee2mqtt**

```
#!/sbin/openrc-run
# Copyright 2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="${SVCNAME} daemon"
description="${DESCRIPTION}"

start() {
  ebegin "Starting ${name}"
    start-stop-daemon --start --quiet --background --make-pidfile \
                --pidfile "${PID:-/run/${SVCNAME}.pid}" \
                --user ${USER:-nobody} \
                --group ${GROUP:-nobody} \
		--chdir "${DIRECTORY}" \
		--exec "${COMMAND}" \
		-- "${OPTIONS}"
  eend $?
}

stop() {
  ebegin "Stopping ${name}"
  start-stop-daemon --stop --pidfile "${PID:-/run/${SVCNAME}.pid}" -R 15
  eend $?
}
```

**/etc/conf.d/zigbee2mqtt**

```
DESCRIPTION='Open source software driver to use zigbee devices without vendors gateway'
DIRECTORY="/home/zigbee2mqtt"
COMMAND="npm"
OPTIONS="start"
USER="zigbee2mqtt"
GROUP="zigbee2mqtt"
PID="/run/zigbee2mqtt.pid"
rc_need="mosquitto"
```

**Comment by xaviermiller** [comment]
Hi,

there is an ebuild for zigbee2mqtt in the inode64 overlay
https://github.com/inode64/inode64-overlay

**Comment by inode64** [comment]
I have the ebuild working without problems for a few months, how could it be integrated with this repository?

**Comment by onkelbeh** [comment]
Thanks @inode64:
https://github.com/onkelbeh/HomeAssistantRepository/tree/master/app-misc/zigbee2mqtt
https://github.com/onkelbeh/HomeAssistantRepository/commit/1fec802637a3d0c7bec49b0ab6c2f7886aabef8f
