### ISSUE TITLE
ebuild for bodymiscale custom addon

### ISSUE THREAD

**Issue by fariouche** [onkelbeh/HomeAssistantRepository#174]
Hello,

This addon is available in ha store, but not here.
I can maybe add it manually... But it would be cool to have it here!
https://github.com/dckiller51/bodymiscale

He also have a card to display the data of the Xiaomi scale.

Side note: this addon retrieves the impedance of the Xiaomi scale and convert it to body mass/fat etc ... The scale is Bluetooth le, and I'm using esphome as a bridge, works 

Thanks 🙏

**Comment by onkelbeh** [comment]
This is a custom component, not a python module.
Should be easy to install: https://github.com/dckiller51/bodymiscale#manual-installation
You need to have cahcetools installed, which is in main repo.

**Comment by fariouche** [comment]
Yes, thank you. I didn't know that they had two type of module.
It seems like custom components are installed using the hacs.
What is cache tools?

**Comment by fariouche** [comment]
They need to be installed in a subdirectory of homeassistant data config folder. I don't know how an ebuild can do that (install inside an other ebuild install folder)
For know I use my own script that install after homeassistant is emerged
