### ISSUE TITLE
HomeAssistant 2022.11.4 + esphome 2022.11.2 build issues

### ISSUE THREAD

**Issue by rastio** [onkelbeh/HomeAssistantRepository#176]
Hello,

I'm rebuilding HA2022.11.4 from scratch due to integration issue (which I might log later) and I found the following dependencies missing from standard gentoo portage tree:

1. dev-python/colorama-0.4.5 (tried 0.4.6, which seems to be working)
https://github.com/onkelbeh/HomeAssistantRepository/blob/616785abe3901a63dabb583e26e797823ee33302/dev-embedded/esphome/esphome-2022.11.2.ebuild#L41
2. dev-python/pyjwt-2.5.0 (I used 2.6.0)
https://github.com/onkelbeh/HomeAssistantRepository/blob/616785abe3901a63dabb583e26e797823ee33302/app-misc/homeassistant/homeassistant-2022.11.4.ebuild#L94
3. media-libs/mutagen-1.45.1 (I used 1.46.0)
https://github.com/onkelbeh/HomeAssistantRepository/blob/616785abe3901a63dabb583e26e797823ee33302/app-misc/homeassistant/homeassistant-2022.11.4.ebuild#L129

Thanks

Rasto

**Comment by onkelbeh** [comment]
mutagen re-added in 1b1f97215

**Comment by onkelbeh** [comment]
colorama pins removed in ebe712b2c
