### ISSUE TITLE
home-assistant-frontend move from app-misc to dev-python

### ISSUE THREAD

**Issue by rastio** [onkelbeh/HomeAssistantRepository#20]
Hello,

thanks for improving HomeAssistant! It seems home-assistant-frontend has been moved from app-misc to dev-python, yet app-misc/home-assistant-frontend is still required in homeassistant-0.111.4.ebuild:

https://github.com/onkelbeh/HomeAssistantRepository/blob/22ed55b7cff266c5e127c23ea7e0b813601d1e99/app-misc/homeassistant/homeassistant-0.111.4.ebuild#L63

All the best
Rasto

**Comment by onkelbeh** [comment]
Oh, missed that.
Should be fixed with https://github.com/onkelbeh/HomeAssistantRepository/commit/db9b91971f0d9cf4506d86942d4be189516bdc61.

**Comment by onkelbeh** [comment]
And added a [fixed Release](https://github.com/onkelbeh/HomeAssistantRepository/releases/tag/v0.112.0_beta2-r1) for it.
