### ISSUE TITLE
HA-2023.1.2 cannot emerge with `otp` USE flag

### ISSUE THREAD

**Issue by zhtengw** [onkelbeh/HomeAssistantRepository#205]
With `otp` USE flag enabled, with which HA depends `~pytop-2.8.0`, HA meet dependency conflict because a `~pytop-2.7.0` is already listed in RDEPEND.
```
RDEPEND="${RDEPEND} 
...
    ~dev-python/pyotp-2.7.0[${PYTHON_USEDEP}]
...
    otp? ( ~dev-python/pyotp-2.8.0[${PYTHON_USEDEP}] )
```

**Comment by onkelbeh** [comment]
fixed in e038471c7 update 2023.1.2-r1, fixes #800,
sorry for the long wait.
