### ISSUE TITLE
homeassistant 2023.1.2 depends on both dev-python/pyotp-2.7.0 and dev-python/pyotp-2.8.0

### ISSUE THREAD

**Issue by abelits** [onkelbeh/HomeAssistantRepository#208]
homeassistant 2023.1.2 depends on both dev-python/pyotp-2.7.0 and dev-python/pyotp-2.8.0 when otp USE flag is enabled.

**Comment by onkelbeh** [comment]
fixed in e038471c7 update 2023.1.2-r1, fixes #800,
sorry for the long wait.
