### ISSUE TITLE
Please update dependency on package "app-crypt/acme"

### ISSUE THREAD

**Issue by cfrancu** [onkelbeh/HomeAssistantRepository#21]
When updating home assistant I got this error:

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "~app-crypt/acme-1.4.0".
(dependency required by "dev-python/hass-nabucasa-0.34.7::HomeAssistantRepository" [ebuild])
(dependency required by "app-misc/homeassistant-0.112.5::HomeAssistantRepository" [ebuild])
(dependency required by "@selected" [set])
(dependency required by "@world" [argument])

I checked the current version for acme, it's 1.6. Could you please update the ebuild dependencies?

Thanks!
Cristian

**Comment by onkelbeh** [comment]
hass-nabucasa-0.34.7 has a fixed dependency to acme-1.4.0 defined in: [setup.py](https://github.com/NabuCasa/hass-nabucasa/blob/master/setup.py), somebody knows why these hardcoded versions are neccesary.

And: unfortunately somebody [removed acme-1.4.0 from the main repo](https://github.com/gentoo/gentoo/commit/87088c8bc31541b706ee482cfee35fe342f362e1#diff-2d8f42223ba0905ba0bb9a553c615308). It was too young to die.

Perhaps we should patch nabucasa, but it has been much easier to add it in https://github.com/onkelbeh/HomeAssistantRepository/commit/4f670ae081258eb5d4fdd469dc20b9fabc1d4f79, it may rest there as long as it's needed.
