### ISSUE TITLE
no ebuilds to satisfy "~dev-python/pynacl-1.3.0

### ISSUE THREAD

**Issue by west17m** [onkelbeh/HomeAssistantRepository#23]
I'm trying to install home assistant from the overlay but it looks like pynacl-1.3.0 is a dependency which is no longer available. I have 1.4.0 installed but that does not satisfy the ebuild.

```
homeassistant` ~ # emerge -av app-misc/homeassistant

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "~dev-python/pynacl-1.3.0[python_targets_python3_7(-)?,python_targets_python3_8(-)?,-python_single_target_python3_7(-),-python_single_target_python3_8(-)]".
(dependency required by "app-misc/homeassistant-0.114.4::HomeAssistantRepository" [ebuild])
(dependency required by "app-misc/homeassistant" [argument])
```
Trying to pull the specific version:

```
homeassistant ~ # emerge -1av =dev-python/pynacl-1.3.0

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy "=dev-python/pynacl-1.3.0".
```

Showing the latest version of pynacl is installed.

```
homeassistant ~ # emerge -1av dev-python/pynacl

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] dev-python/pynacl-1.4.0::gentoo  USE="-test" PYTHON_TARGETS="python3_7 -python3_6 -python3_8 (-python3_9)" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

```

Thank you for maintaining the overlay.

**Comment by west17m** [comment]
Here is a patch bumping versions of a few of the packages to fix the above and other conflicts. This now builds on my system system. Thanks again.

[2020-09-01-version-bump.patch](https://pastebin.com/raw/jLzPHib1)

**Comment by onkelbeh** [comment]
Seems that dev-python/pynacl-1.3.0 was thrown out main repo: https://github.com/gentoo/gentoo/commit/21a7167f8babba5b5e7a7396a4a3acd8b7111328#diff-d5522a6e9915cf75cf9dac008256fedd.

Just added a copy: https://github.com/onkelbeh/HomeAssistantRepository/commit/c228629483e6a8682c2f41dc85f59ed8b7dc4078

**Comment by onkelbeh** [comment]
Your patch won't solve the problem, PyNaCl is pinned to 1.3.0,
you now have 1.4.0 installed in site-packages, so HA will download it's own copy of 1.3.0 to `/etc/homeassistant/deps`, what we want to avoid.

```
root@g18-hass:/usr/lib/python3.7/site-packages/homeassistant # grep -ir pynacl
package_constraints.txt:PyNaCl==1.3.0
components/mobile_app/manifest.json:  "requirements": ["PyNaCl==1.3.0", "emoji==0.5.4"],
components/owntracks/manifest.json:  "requirements": ["PyNaCl==1.3.0"],
```

Why are you using the old home-assistant-cli-0.7.0?
```
[I] app-misc/home-assistant-cli [1]
     Verfügbare Versionen:   (~)0.7.0 (~)0.8.0 (~)0.9.0 (~)0.9.1{xpak} ~9999*l{xpak:4} {test PYTHON_TARGETS="python3_6 python3_7 python3_8"}
     Installierte Versionen: 0.9.1{xpak}(11:58:34 01.08.2020)(-test PYTHON_TARGETS="python3_7 -python3_6 -python3_8")
     Startseite:             https://github.com/home-assistant/home-assistant-cli/
     Beschreibung:           The Home Assistant Command-line Interface (hass-cli)
```
I use 0.9.1 on the production box, but also the dev ebuild compiles fine.


Also I have convertdate-2.2.1-r1 running, you should not use the old one.
```
[I] dev-python/convertdate [1]
     Verfügbare Versionen:   ~2.1.3 (~)2.2.1-r1{tbz2} {test PYTHON_TARGETS="python3_6 python3_7 python3_8"}
     Installierte Versionen: 2.2.1-r1{tbz2}(20:47:16 23.05.2020)(-test PYTHON_TARGETS="python3_7 -python3_6 -python3_8")
     Startseite:             https://github.com/fitnr/convertdate https://pypi.org/project/convertdate/
     Beschreibung:           Converts between Gregorian dates and other calendar systems.
```

The limit of `convertdate-2.1.3` is set correctly according to https://github.com/fitnr/convertdate/blob/v2.1.3/setup.py

I [fixed `numpy-1.19.1`'s Cython>=0.29.21 requirement](https://github.com/onkelbeh/HomeAssistantRepository/commit/f641807df51367c9dce1d07f18c9eff363e67a45). Missed that one, sorry.

Thanks for reporting!

**Comment by west17m** [comment]
> Your patch won't solve the problem, PyNaCl is pinned to 1.3.0,
> you now have 1.4.0 installed in site-packages, so HA will download it's own copy of 1.3.0 to `/etc/homeassistant/deps`, what we want to avoid.

You are correct. I mainly stick to the main portage tree so I'm not 100% familiar with custom ebuilds and overlays. It took me a while to figure out the ebuild structure, how to build a manifest, and generate a patch. I didn't realize HA would pull in dependencies like that. 

> Why are you using the old home-assistant-cli-0.7.0?

That wasn't my intention. I unmasked the specific version apparently while trying to fix the dependencies. I'm recompiling now.

> Also I have convertdate-2.2.1-r1 running, you should not use the old one.

Unmasking the whole package as well and recompiling. Thanks again, this is a great overlay.

**Comment by onkelbeh** [comment]
HA downloads almost all deps from it's `'requirements.txt'` which are not already fulfilled ,
it cannot do this for most of the deps from `'package_constraints.txt'`.
I try to have ebuilds for all these packages anyway, my `'/etc/homeassistant/deps'` is empty, I remove all files in there before restarts.

You are very welcome.
