### ISSUE TITLE
custom_quirks_path parameter of zhaquirks setup() is present in app-misc/homeassistant-2023.3.6 but is not supported with zhaquirks version installed with it

### ISSUE THREAD

**Issue by abelits** [onkelbeh/HomeAssistantRepository#232]
In my configuration with app-misc/homeassistant-2023.3.6 installed, file
/usr/lib/python3.10/site-packages/homeassistant/components/zha/__init__.py

contains a line:
`setup_quirks(custom_quirks_path=config.get(CONF_CUSTOM_QUIRKS_PATH))`

This calls setup() from
/etc/homeassistant/deps/lib/python3.10/site-packages/zhaquirks/__init__.py
that is defined as:

`def setup(config: Optional[Dict[str, Any]] = None) -> None:`

The call matches dev-python/zha-quirks-0.94, its /usr/lib/python3.10/site-packages/zhaquirks/__init__.py contains setup() defined as:
`def setup(custom_quirks_path: str | None = None) -> None:`

To fix the problem I have installed dev-python/zha-quirks-0.94 and removed /etc/homeassistant/deps/lib/python3.10/site-packages/zhaquirks

Is there something that should automatically replace those packages?

**Comment by onkelbeh** [comment]
```bash
root@g18-hasstest:/usr/portage/homeassistant/app-misc/homeassistant-min # grep -ir zha-qui
homeassistant-min-2023.3.6.ebuild:	zha? ( ~dev-python/bellows-0.34.10[${PYTHON_USEDEP}] ~dev-python/pyserial-3.5[${PYTHON_USEDEP}] ~dev-python/pyserial-asyncio-0.6[${PYTHON_USEDEP}] ~dev-python/zha-quirks-0.0.94[${PYTHON_USEDEP}] ~dev-python/zigpy-deconz-0.19.2[${PYTHON_USEDEP}] ~dev-python/zigpy-0.53.2[${PYTHON_USEDEP}] ~dev-python/zigpy-xbee-0.16.2[${PYTHON_USEDEP}] ~dev-python/zigpy-zigate-0.10.3[${PYTHON_USEDEP}] ~dev-python/zigpy-znp-0.9.3[${PYTHON_USEDEP}] )
```
2023.3.6 needs zha-quirks-0.94, and it is correctly referenced in the ebuilds.
Cannot explain how you got the wrong version. You did not mention the wrong version installed.

<img width="1040" alt="grafik" src="https://user-images.githubusercontent.com/42828703/231888111-0d8eec66-bd7d-4e86-9e1f-c10283522d3c.png">
