### ISSUE TITLE
Missing ~dev-python/attrs-22.2.0 dep for  app-misc/homeassistant-full-2023.4.6:

### ISSUE THREAD

**Issue by Retidurc** [onkelbeh/HomeAssistantRepository#261]
Hello, ~dev-python/attrs-22.2.0 seems to have been removed from gentoo main tree some time ago [in this commit](https://github.com/gentoo-mirror/gentoo/commit/05133cd5595ec58ebf1d94ab909370a136d824dd)

For now, only attrs-23.1.0 is in the main tree, should the homeassistant ebuild be updated or should this overlay reintroduce the older attrs ? I'll happily provide a pr if needed ( at least if I found the time to do so)

**Comment by onkelbeh** [comment]
Yep, but please send PR to https://git.edevau.net/onkelbeh/HomeAssistantRepository,
also, please take a look at https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/1527

**Comment by onkelbeh** [comment]
<img width="935" alt="grafik" src="https://github.com/onkelbeh/HomeAssistantRepository/assets/42828703/7eb01230-8399-4105-b07c-abab96563368">
