### ISSUE TITLE
dev-python/reedsolomon missing

### ISSUE THREAD

**Issue by rastio** [onkelbeh/HomeAssistantRepository#267]
Hello,

esptool is requesting dev-python/reedsolomon which is not part of gentoo tree anymore, probably changed name to dev-python/reedsolo

https://github.com/onkelbeh/HomeAssistantRepository/blob/0670b4e97dab49f21bc719d42e7c20d9e65694b2/dev-embedded/esptool/esptool-4.5.1.ebuild#L25

Can you please add it to your dev-python repository.

Thanks for all the work

Rasto

**Comment by gerion0** [comment]
`esptool` also exists in the [main Gentoo tree](https://packages.gentoo.org/packages/dev-embedded/esptool) (even in newer version). Are there some differences to the one provided in this repo?

**Comment by BillKen** [comment]
Hi, yes reedsolomon is no longer in the gentoo tree and the gentoo ebuilds have been updated to use "reedsolo"
Gentoo also no longer has version esptool-4.4 (requirements.txt) so building fails.
BillK

**Comment by onkelbeh** [comment]
looks outdated now, will cleanup the dupe and the old version with the next release.
