### ISSUE TITLE
Upgrade to 2023.8.1 & all dependencies to python 3.11

### ISSUE THREAD

**Issue by CyberGuerro** [onkelbeh/HomeAssistantRepository#268]
As in the title I'm asking for product upgrade (with all the dependencies).
4 months are passed  since last upgrade....... I hope this isn't became a dead project/package.....  Now no more compatible with gentoo's actual distribution.

**Comment by tabascoz** [comment]
hi, happy to support in any way i can... i had to create some local ebuilds to update gentoo and deal with python 11, would be nice to see an upgrade to current version. Thanks

**Comment by CyberGuerro** [comment]
@tabascoz , if you have ebuild greater then 2.4.6, could you attach it here as it could be the starting point for new 2023.8.x release and meanwhile we could use it (with your permission) as our local ebuild.

**Comment by fariouche** [comment]
Hello,
Please note that the autor is still working on this, but due to a major change in Gentoo, a lot of ebuilds need to be updated! This is a nightmare.
But he's doing his best to make it working again.
Please see the original repo in his own GitHub server, this one is merely a mirror.
Any help is appreciated, please support him 👍

**Comment by CyberGuerro** [comment]
I noticed that new package (223.10.4) depend on missing package:
**- dev-python/protobuf-python-4.24.3**

and these packages (dependencies of homeassistant-full-2023.10.4):
**- dev-python/grpcio-1.58.0:0/0::HomeAssistantRepository**
**- dev-python/grpcio-reflection-1.58.0:0/0::HomeAssistantRepository**
**- dev-python/grpcio-status-1.58.0:0/0::HomeAssistantRepository**
**- dev-python/dbus-fast-2.12.0:0/0::HomeAssistantRepository**
 require cython < 3, but package **dev-python/zeroconf-0.115.2:0** (required by homeassistant-full-2023.10.4) require cython >=3

I suspect that grpcio* have to be updated removing constraint
**<dev-python/cython-3[${PYTHON_USEDEP}]"**
