### ISSUE TITLE
dev-python/aiohttp-retry on ::science

### ISSUE THREAD

**Issue by TheChymera** [onkelbeh/HomeAssistantRepository#274]
I recently packaged dev-python/aiohttp-retry which we needed for ::science 
Started off with your ebuild but noticed that the tests didn't pass.
I fixed that → https://github.com/gentoo/sci/commit/39aa26e66beae16887de80286c1e97baf6432981
Feel free to reuse, or maybe we can get this merged in ::gentoo so that we don't have to maintain it separately.

**Comment by onkelbeh** [comment]
Thanks, merged it.
I have 1827 more where it's coming from 🤣.

Missing tests are a very common practice for Pypi's SDISTs,
I gave up on commenting, often this leads to wild includes, which then cause top level violations.

Currently I disabled testing on my dev box, insufficient time for maintaining too much stuff...

![grafik](https://github.com/onkelbeh/HomeAssistantRepository/assets/42828703/8cabe561-ec6f-48f3-ac6d-b7014891fe71)
