### ISSUE TITLE
[q] Make hass-nabucasa dependency only with cloud flag

### ISSUE THREAD

**Issue by SkeLLLa** [onkelbeh/HomeAssistantRepository#28]
Is it possible to make hass-nabucasa optional dependency that's enabled only when `cloud` flag is present for basic and full packages?
https://github.com/onkelbeh/HomeAssistantRepository/blob/master/app-misc/homeassistant-full/homeassistant-full-0.117.5.ebuild#L62

**Comment by onkelbeh** [comment]
I am afraid this won't help, because hass-nabucasa is pulled in from package_constraints.txt.
This was changed in Home Assistant about a half year ago, formerly this has been a regular component.

**Comment by SkeLLLa** [comment]
Ok, thanks for clarification.

**Comment by onkelbeh** [comment]
Perhaps you can file a question at the Nabucasa Site.
I believe this was done to force selling Nabucasa Accounts.
I know this thing has some inconvenient hardly pinned dependencies.
