### ISSUE TITLE
git server not functioning

### ISSUE THREAD

**Issue by pvint** [onkelbeh/HomeAssistantRepository#29]
fatal: unable to access 'https://git.edevau.net/onkelbeh/HomeAssistantRepository.git/': The requested URL returned error: 503

**Comment by onkelbeh** [comment]
Yep, sorry for that, gitea-1.12.4 seems to crash frequently.
Will update to 1.12.6 soon.

For now I started it again.

**Comment by pvint** [comment]
No worries - thanks!
