### ISSUE TITLE
dev-embedded/esptool-3.1: undeclared dependencies

### ISSUE THREAD

**Issue by salfter** [onkelbeh/HomeAssistantRepository#40]
dev-embedded/esptool-3.1 won't build without dev-python/pip and dev-python/wheel, but these aren't declared in BDEPEND.

**Comment by onkelbeh** [comment]
Yeah, pip could be, it's mostly installed on my test boxes, but I don't have wheel on them.
Will check this out further with the next full build. Thanks for reporting.
