### ISSUE TITLE
ecobee integration changed required library

### ISSUE THREAD

**Issue by jayofdoom** [onkelbeh/HomeAssistantRepository#41]
The ecobee integration now uses `pyecobee` (https://pypi.org/project/pyecobee/) instead of `python-ecobee-api`.

As an added problem, `python-ecobee-api` uses the same `ecobee` python module name as `pyecobee`, and having it installed prevents homeassistant's built-in dep resolver from fixing the issue, and causes this error:

```
Aug 15 03:58:10 durex hass[13825]: 2021-08-15 03:58:10 ERROR (MainThread) [homeassistant.setup] Setup failed for ecobee: Unable to import component: cannot import name 'ECOBEE_API_KEY' from 'pyecobee' (unknown location)
Aug 15 04:05:15 durex hass[13825]: 2021-08-15 04:05:15 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration ecobee: cannot import name 'ECOBEE_API_KEY' from 'pyecobee' (unknown location)
```

At a minimum, the `ecobee` use flag and `python-ecobee-api` package should be removed. Best case, you could add an ebuild for pyecobee. 

There is a small chance I might attempt to tackle a pull request for this myself, if you're disinterested :).

**Comment by onkelbeh** [comment]
Please take a look at the current dev-Tree:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/ecobee/manifest.json,
I share this opinion with my build script tells the same with the 2021.8.8 Ebuilds:

```bash
root@g18-hasstest:~ # hass --version
2021.8.8
root@g18-hasstest:~ # cat /usr/lib/python3.9/site-packages/homeassistant/components/ecobee/manifest.json
{
  "domain": "ecobee",
  "name": "ecobee",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/ecobee",
  "requirements": ["python-ecobee-api==0.2.11"],
  "codeowners": ["@marthoc"],
  "iot_class": "cloud_polling"
}
root@g18-hasstest:~ #
```

Currently it is pulling it from Pypi: https://pypi.org/project/python-ecobee-api/, which references https://github.com/nkgilley/python-ecobee-api.

Can you please explain where your information is taken from?
