### ISSUE TITLE
emoji-1.5.0

### ISSUE THREAD

**Issue by rastio** [onkelbeh/HomeAssistantRepository#43]
Hello,

I believe there is an issue with emoji-1.5.0 dependency, when building for x86

(1) emoji-1.5.0 has been removed from standard gentoo portage tree - so portage cannot get it from there
or
(2) dev-python/emoji/emoji-1.5.0.ebuild included in HomeAssistantRepository does not have x86 nor ~x86 keyword

I'm sorry, but I do not have enough experience to suggest solution.

Thank you for all the work

Rasto

**Comment by onkelbeh** [comment]
Keywords extended in commit f69af1e11bf884dd2cc7ad43f546dddbc85e1506
