### ISSUE TITLE
not all ebuilds have a arm or arm64 flag

### ISSUE THREAD

**Issue by Shaggy013** [onkelbeh/HomeAssistantRepository#46]
Hello

Always thought bavaria was a dutch beer brand :)

not all ebuilds have the arm or arm64 flag .

**Comment by onkelbeh** [comment]
do you need a special one?

**Comment by Shaggy013** [comment]
no but as you do minium it womt build ,si your portageoverlay doesnt workOn 20 Dec 2021 07:55, Andreas Billmeier ***@***.***> wrote:
do you need a special one?
