### ISSUE TITLE
missing hass_frontend in site-package

### ISSUE THREAD

**Issue by fariouche** [onkelbeh/HomeAssistantRepository#47]
Hello,

First, thank you so much about this repo, this is a huge time saver, so many dependencies!
I have almost sorted my various issues, and I think that this is the last one...
I can see that the dependency home-assistant-frontend is installed, but hass complains about missing hass_frontend module.
Looking at the python site-package, I can indeed see that home-assistant-frontend eggfile is here, but not the hass_frontend folder.
When emerging the package, I can see a lot of yarn warning, but nothing serious... at the end, I see also that the packaging is not using the hass_frontend folder...

I wonder, because I found this other way of installing the package and it's totally different: https://github.com/openlumi/homeassistant_on_openwrt/blob/21.02/ha_install.sh

They are getting the archive from pypi and just copy its content (after removing uneeded files)

I'm of course using latest ~amd64, python3.9.

By the way, I tried to build it myself, without ebuild, when doing python setup.py install, I can see that hass_frontend is indeed installed in the build directory.

If you have an idea on why, it will help! Thank you!

**Comment by onkelbeh** [comment]
Yes, sorry, already know, the SDIST we used as a source is not provided anymore due to space restrictions at Pypi. Will be fixed as soon as possible.

**Comment by onkelbeh** [comment]
Dupe to https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/259
also mentioned in https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues/258

**Comment by fariouche** [comment]
thank you! I will check the readings :)
They seem overwhelmed and doing maintenance simplifications. They are even promoting the docker version because it's so more simple for them (I can understand). But like you, I try to maintain my server as clean as possible, and avoid using docker, venv and huge amount of duplicate packages everywhere that end up with wasted gigs of disk :(

**Comment by onkelbeh** [comment]
Should be working again after https://github.com/onkelbeh/HomeAssistantRepository/commit/ce2d37ebe89f0d5e92430da963d0f79193481946, could you please try?
Close the ticket if it works for you.

**Comment by RayOfLight1** [comment]
Dayum, it fixed it for me! ty.

**Comment by fariouche** [comment]
top +1! thanks!
