### ISSUE TITLE
Cannot install dev-python/envs-1.4

### ISSUE THREAD

**Issue by fariouche** [onkelbeh/HomeAssistantRepository#48]
Hello,

I tried to install latest home assistant 3.0.
When updating, I got an error when emerging envs 1.4
error in envs setup command: 'extras_require' must be a dictionary whose values are strings or list of strings containing valid project/version requirement specifiers.

In my case I have this use flags: "-cli% -test" 
Python targets: python 3.9

I will try to add the cli use flag, maybe this will solve the issue

**Comment by fariouche** [comment]
well, with +cli, it complains about missing jinja2 ebuild

**Comment by fariouche** [comment]
Trying to set the jinja version to 3 and +cli fixes the installation (however, I don't know if envs is compatible with jinja 3 as it in the ebuild it was specified jinja2)

**Comment by onkelbeh** [comment]
There's a problem in upstream's setup.py, not sure how it went through the tests, they do not tag releases on Github. You can use dev-python/envs-1.3-r1 with Home Assistant until this is fixed.

**Comment by onkelbeh** [comment]
Please try again.
