### ISSUE TITLE
dev-python/importlib-metadata confilct with the dev-python/importlib_metadata in Gentoo repository

### ISSUE THREAD

**Issue by zhtengw** [onkelbeh/HomeAssistantRepository#7]
The app-misc/homeassistant depends on dev-python/importlib-metadata in this repository. But dev-python/importlib_metadata in Gentoo repository supply the same files with dev-python/importlib-metadata.

**Comment by onkelbeh** [comment]
Yep, you are right, my script did not find it, imho _they_ picked the wrong name.
Corrected in https://github.com/onkelbeh/HomeAssistantRepository/commit/1b0f5bfe3758ad4b815d99e78739a08cf3f7219b
Left the dupe ebuild for easier removal, the -r1 from main repo will win anyway.
