### ISSUE TITLE
dev-embedded/esptool possible dependency problem

### ISSUE THREAD

**Issue by expeditioneer** [onkelbeh/HomeAssistantRepository#73]
Current Runtime Dependencies contains

```
>=dev-python/reedsolomon-1.5.3[${PYTHON_USEDEP}]
<=dev-python/reedsolomon-1.5.4[${PYTHON_USEDEP}]
```

but portage contains only [dev-python/reedsolomon](https://packages.gentoo.org/packages/dev-python/reedsolomon) in version _1.5.4-r1_ and is not considered due to the version restriction. Because of that the emerge of esphome is blocked in the end.

**Comment by onkelbeh** [comment]
just re-checked, everything is OK with 1.5.4, please re-open if you have any issues.
