### ISSUE TITLE
Dependency issue with sqlalchemy and pscopg2

### ISSUE THREAD

**Issue by fariouche** [onkelbeh/HomeAssistantRepository#96]
Hello,

Just to let you know that I just upgrade to latest version today, and got an issue: sqlalchemy complains about missing package pscopg2.

In fact, in my gentoo, pscopg package pull the version 3. I have to pull myself pscopg:2 for use the slot 2 version.

Not directly a homeassistant bug, mostlikely a bug in the slqalchemy ebuild. I see no package that depends on pscopg:2.

I'm using postgreql with the recorder module. 

Hope this helps

**Comment by onkelbeh** [comment]
Looks like using :2 is correct:

<img width="464" alt="grafik" src="https://user-images.githubusercontent.com/42828703/179800930-0109d0ab-4b75-4978-a6d7-87d9f19f21f4.png">

I don't know why they don't put it in a Useflag. The Ebuild is taken from Gentoo Github Archive.

**Comment by fariouche** [comment]
Yes, I know. I only reported it to you to avoid you to search for the issue when you will face it :)

**Comment by onkelbeh** [comment]
Unfortunately I have no skills on postgres, my recorder writes to a mariadb.
